test

diff --git a/.github/workflows/pr-deploy.yml b/.github/workflows/pr-deploy.yml
--- a/.github/workflows/pr-deploy.yml
+++ b/.github/workflows/pr-deploy.yml
@@ -38,10 +38,12 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up Google Cloud SDK
+        id: auth
         uses: google-github-actions/auth@v2
         with:
           credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_KEY }}
           service_account: github@qualified-gist-454616-m5.iam.gserviceaccount.com
+          export_environment_variables: true
 
       - name: Set up Cloud SDK
         uses: google-github-actions/setup-gcloud@v2
@@ -53,6 +55,9 @@ jobs:
         id: setup-db
         run: |
           chmod +x .ci/setup-database.sh
+          echo "Using Google Application Credentials: $GOOGLE_APPLICATION_CREDENTIALS"
+          # Verify credentials file exists
+          ls -la $GOOGLE_APPLICATION_CREDENTIALS || echo "Credentials file not found!"
           .ci/setup-database.sh ${{ github.event.pull_request.number }}
 
   build-and-push-frontend:
